"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Share2,
  Copy,
  Check,
  MessageCircle,
  Link2,
  Eye,
  GraduationCap,
  Target,
  TrendingUp,
  IndianRupee,
  MapPin,
  Calendar,
  Briefcase,
  Mail,
  Download,
} from "lucide-react"

const roadmapData = {
  studentName: "Rahul Sharma",
  class: "Class 11 - Science",
  generatedDate: "April 21, 2026",
  viabilityScore: 87,
  topCareer: "Software Engineer",
  matchPercentage: 92,
  estimatedSalary: "₹12.5 LPA",
  marketGrowth: "+42%",
  recommendedColleges: [
    { name: "IIT Bombay", fees: "₹8.5L", rank: "#1" },
    { name: "BITS Pilani", fees: "₹20L", rank: "#2" },
    { name: "IIIT Hyderabad", fees: "₹10L", rank: "#3" },
  ],
  timeline: [
    { phase: "Now - Dec 2026", action: "JEE Preparation + Coding Practice" },
    { phase: "Jan - Apr 2027", action: "JEE Mains & Advanced" },
    { phase: "Jun 2027", action: "College Counseling & Admission" },
    { phase: "2027-2031", action: "B.Tech Computer Science" },
  ],
  interests: ["Technology & Coding", "Mathematics", "Problem Solving"],
  budget: "₹15-20 Lakhs",
  preferredCities: ["Bangalore", "Mumbai", "Hyderabad"],
}

export default function ShareSummaryPage() {
  const [copied, setCopied] = useState(false)
  const [shareSettings, setShareSettings] = useState({
    includeFinancials: true,
    includeTimeline: true,
    includeColleges: true,
    expiryDays: "30",
  })

  const shareLink = "https://parentanchor.com/s/rahul-roadmap-abc123"

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareLink)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleWhatsAppShare = () => {
    const message = encodeURIComponent(
      `Check out Rahul's Career Roadmap on ParentAnchor!\n\n` +
        `Top Career Match: ${roadmapData.topCareer} (${roadmapData.matchPercentage}% match)\n` +
        `Financial Viability Score: ${roadmapData.viabilityScore}/100\n\n` +
        `View full roadmap: ${shareLink}`
    )
    window.open(`https://wa.me/?text=${message}`, "_blank")
  }

  const handleEmailShare = () => {
    const subject = encodeURIComponent(
      `${roadmapData.studentName}'s Career Roadmap - ParentAnchor`
    )
    const body = encodeURIComponent(
      `Hi,\n\nI wanted to share ${roadmapData.studentName}'s personalized career roadmap generated by ParentAnchor.\n\n` +
        `Top Career Match: ${roadmapData.topCareer} (${roadmapData.matchPercentage}% match)\n` +
        `Financial Viability Score: ${roadmapData.viabilityScore}/100\n` +
        `Estimated Starting Salary: ${roadmapData.estimatedSalary}\n\n` +
        `View the full roadmap here: ${shareLink}\n\n` +
        `Best regards`
    )
    window.open(`mailto:?subject=${subject}&body=${body}`, "_blank")
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-foreground">Share Roadmap Summary</h1>
        <p className="text-muted-foreground">
          Generate a shareable snapshot of {roadmapData.studentName}&apos;s career roadmap
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Preview Card */}
        <div className="lg:col-span-2">
          <Card className="border-border">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="flex items-center gap-2 text-foreground">
                    <Eye className="h-5 w-5 text-secondary" />
                    Preview
                  </CardTitle>
                  <CardDescription>
                    This is how your shared summary will look
                  </CardDescription>
                </div>
                <Badge variant="outline" className="text-xs">
                  Last updated: {roadmapData.generatedDate}
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              {/* Roadmap Snapshot Preview */}
              <div className="rounded-xl border-2 border-border bg-card p-6">
                {/* Header */}
                <div className="mb-6 border-b border-border pb-6">
                  <div className="flex items-center gap-3">
                    <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-primary-foreground">
                      <GraduationCap className="h-7 w-7" />
                    </div>
                    <div>
                      <h2 className="text-xl font-bold text-foreground">
                        {roadmapData.studentName}
                      </h2>
                      <p className="text-muted-foreground">{roadmapData.class}</p>
                    </div>
                  </div>
                </div>

                {/* Viability Score */}
                <div className="mb-6 rounded-lg bg-secondary/10 p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Target className="h-6 w-6 text-secondary" />
                      <div>
                        <p className="text-sm text-muted-foreground">
                          Financial Viability Score
                        </p>
                        <p className="text-2xl font-bold text-foreground">
                          {roadmapData.viabilityScore}/100
                        </p>
                      </div>
                    </div>
                    <Badge className="bg-secondary text-secondary-foreground">
                      Excellent
                    </Badge>
                  </div>
                </div>

                {/* Top Career */}
                <div className="mb-6 space-y-4">
                  <h3 className="font-semibold text-foreground">Top Career Match</h3>
                  <div className="flex items-center justify-between rounded-lg border border-border p-4">
                    <div className="flex items-center gap-4">
                      <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary">
                        <Briefcase className="h-6 w-6" />
                      </div>
                      <div>
                        <p className="font-semibold text-foreground">
                          {roadmapData.topCareer}
                        </p>
                        <div className="flex items-center gap-3 text-sm text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <TrendingUp className="h-3 w-3 text-green-600" />
                            {roadmapData.marketGrowth} growth
                          </span>
                          <span>{roadmapData.estimatedSalary}</span>
                        </div>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-2xl font-bold text-secondary">
                        {roadmapData.matchPercentage}%
                      </p>
                      <p className="text-xs text-muted-foreground">Match</p>
                    </div>
                  </div>
                </div>

                {/* Recommended Colleges */}
                {shareSettings.includeColleges && (
                  <div className="mb-6 space-y-4">
                    <h3 className="font-semibold text-foreground">
                      Recommended Colleges
                    </h3>
                    <div className="grid gap-2">
                      {roadmapData.recommendedColleges.map((college, index) => (
                        <div
                          key={index}
                          className="flex items-center justify-between rounded-lg border border-border p-3"
                        >
                          <div className="flex items-center gap-3">
                            <span className="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-sm font-bold text-muted-foreground">
                              {college.rank}
                            </span>
                            <span className="font-medium text-foreground">
                              {college.name}
                            </span>
                          </div>
                          <span className="text-sm text-muted-foreground">
                            {college.fees}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Timeline */}
                {shareSettings.includeTimeline && (
                  <div className="mb-6 space-y-4">
                    <h3 className="font-semibold text-foreground">Roadmap Timeline</h3>
                    <div className="space-y-3">
                      {roadmapData.timeline.map((item, index) => (
                        <div key={index} className="flex items-start gap-3">
                          <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-bold text-secondary-foreground">
                            {index + 1}
                          </div>
                          <div>
                            <p className="text-sm font-medium text-foreground">
                              {item.phase}
                            </p>
                            <p className="text-sm text-muted-foreground">
                              {item.action}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Budget & Preferences */}
                {shareSettings.includeFinancials && (
                  <div className="space-y-4">
                    <h3 className="font-semibold text-foreground">
                      Budget & Preferences
                    </h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="flex items-center gap-2">
                        <IndianRupee className="h-4 w-4 text-muted-foreground" />
                        <span className="text-sm text-muted-foreground">Budget:</span>
                        <span className="text-sm font-medium text-foreground">
                          {roadmapData.budget}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        <MapPin className="h-4 w-4 text-muted-foreground" />
                        <span className="text-sm text-muted-foreground">Cities:</span>
                        <span className="text-sm font-medium text-foreground">
                          {roadmapData.preferredCities.slice(0, 2).join(", ")}
                        </span>
                      </div>
                    </div>
                  </div>
                )}

                {/* Footer */}
                <div className="mt-6 border-t border-border pt-4 text-center">
                  <p className="text-xs text-muted-foreground">
                    Generated by ParentAnchor • {roadmapData.generatedDate}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Share Options */}
        <div className="space-y-6">
          {/* Share Settings */}
          <Card className="border-border">
            <CardHeader>
              <CardTitle className="text-foreground">Share Settings</CardTitle>
              <CardDescription>Customize what to include in the summary</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <Label htmlFor="financials" className="cursor-pointer">
                  Include Financial Details
                </Label>
                <Switch
                  id="financials"
                  checked={shareSettings.includeFinancials}
                  onCheckedChange={(checked) =>
                    setShareSettings({ ...shareSettings, includeFinancials: checked })
                  }
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="timeline" className="cursor-pointer">
                  Include Timeline
                </Label>
                <Switch
                  id="timeline"
                  checked={shareSettings.includeTimeline}
                  onCheckedChange={(checked) =>
                    setShareSettings({ ...shareSettings, includeTimeline: checked })
                  }
                />
              </div>
              <div className="flex items-center justify-between">
                <Label htmlFor="colleges" className="cursor-pointer">
                  Include College Recommendations
                </Label>
                <Switch
                  id="colleges"
                  checked={shareSettings.includeColleges}
                  onCheckedChange={(checked) =>
                    setShareSettings({ ...shareSettings, includeColleges: checked })
                  }
                />
              </div>
              <div className="space-y-2 pt-2">
                <Label htmlFor="expiry">Link Expires After</Label>
                <select
                  id="expiry"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  value={shareSettings.expiryDays}
                  onChange={(e) =>
                    setShareSettings({ ...shareSettings, expiryDays: e.target.value })
                  }
                >
                  <option value="7">7 days</option>
                  <option value="30">30 days</option>
                  <option value="90">90 days</option>
                  <option value="never">Never</option>
                </select>
              </div>
            </CardContent>
          </Card>

          {/* Share Link */}
          <Card className="border-border">
            <CardHeader>
              <CardTitle className="text-foreground">Share Link</CardTitle>
              <CardDescription>Copy or share via messaging apps</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  value={shareLink}
                  readOnly
                  className="flex-1 text-sm"
                />
                <Button
                  variant="outline"
                  size="icon"
                  onClick={handleCopyLink}
                  className="shrink-0"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-600" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </Button>
              </div>

              <div className="grid gap-2">
                <Button
                  className="w-full justify-start gap-3 bg-green-600 hover:bg-green-700"
                  onClick={handleWhatsAppShare}
                >
                  <MessageCircle className="h-5 w-5" />
                  Share on WhatsApp
                </Button>
                <Button
                  variant="outline"
                  className="w-full justify-start gap-3"
                  onClick={handleEmailShare}
                >
                  <Mail className="h-5 w-5" />
                  Share via Email
                </Button>
                <Button
                  variant="outline"
                  className="w-full justify-start gap-3"
                >
                  <Download className="h-5 w-5" />
                  Download as PDF
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Tips */}
          <Card className="border-secondary/30 bg-secondary/5">
            <CardContent className="p-4">
              <p className="text-sm text-muted-foreground">
                <strong className="text-foreground">Tip:</strong> Share this summary with 
                family members and school counselors to get their input on the career 
                roadmap.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
